### ISSUE TITLE
mutations versus homologous recombination (r/m)

### ISSUE THREAD

**Issue by Thexiyang** [alexcritschristoph/soil_popgen#5]
Hi. One question on the r/m. I did not find r/m values in the inStrain output. In the paper, it said: "The relative rate of recombination to mutation (gamma/mu) for each population was calculated using the mcorr package (cite) on synonymous third position codon sites across filtered mapped reads from all samples. " This is not clear to me. Could you provide some further guidance to calculate  this parameter based on output from inStrain? Thanks!

**Comment by alexcritschristoph** [comment]
Hello, that metric was calculated in the paper using mcorr:
https://www.nature.com/articles/s41592-018-0293-7
https://github.com/kussell-lab/mcorr
