### ISSUE TITLE
No module named 'allel'

### ISSUE THREAD

**Issue by ChenTianYi99** [alexcritschristoph/soil_popgen#8]
Hi,
I have successfully installed inStrain_lite.
However, when I try 'python fst.py' command, I encountered 'ModuleNotFoundError: No module named 'allel'. It seems 'allel' could not be installed via pip. How to fix it?

Thanks in advance.

**Comment by alexcritschristoph** [comment]
Here's the scikit allel package:
https://scikit-allel.readthedocs.io/en/stable/

Note the code in this repo is several years old, and no longer maintained - you might prefer using inStrain: https://instrain.readthedocs.io/
