### ISSUE TITLE
Generate inStrain object for fst calculation

### ISSUE THREAD

**Issue by ChenTianYi99** [alexcritschristoph/soil_popgen#9]
Hi, 
i have run inStrain to profile microdiversity of viral populations and the tool produced a variety of output in the "NAME_profile" folder (scaffold_info.tsv, gene_info.tsv, genome_info.tsv, linkage.tsv, mapping_info.tsv, scaffold_info.tsv, SNVs.tsv). 

In downstream analyses, i tried to use fst.py to calculate Fst values for paired species but i could not find "Name_profile.data". Should i run inStrain_lite to generate this file instead of inStrain?

Thanks in advance.

**Comment by alexcritschristoph** [comment]
Probably the best route here would be to write some new python code with scikit-allel to calculate Fst from the inStrain SNVs table.
